name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
           
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'

    - name: Create json file
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: presales-gdrive-service.json
        json: ${{secrets.GD_SERVICE_ACCOUNT}}

    - name: Move files
      run: |
        mkdir -p $HOME/gdrive
        cp presales-gdrive-service.json $HOME/gdrive
        ls -ltr $HOME/gdrive

    - name: Build and test
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: ./mvnw -B clean verify -DskipTests

    - name: Copy artifacts for staging
      run: |
        mkdir staging
        cp target/*.zip staging
        cp target/*.jar staging

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Connectors
        path: staging
